

function LayoutTest(){
    return (<>
    <section id="page1">
        <h1>PAGE 1</h1>
        this is a section.

        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sagittis vitae et leo duis. Sed risus pretium quam vulputate dignissim suspendisse in est. Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Lacus laoreet non curabitur gravida arcu ac. Est ante in nibh mauris cursus. Viverra mauris in aliquam sem. Justo laoreet sit amet cursus sit amet dictum sit amet. Turpis egestas pretium aenean pharetra. Ut enim blandit volutpat maecenas volutpat. Odio ut sem nulla pharetra diam sit. Felis imperdiet proin fermentum leo vel orci porta. Et pharetra pharetra massa massa. Arcu risus quis varius quam quisque id. Tempus urna et pharetra pharetra massa massa ultricies mi. Nisl nisi scelerisque eu ultrices. Sed velit dignissim sodales ut eu. Porttitor rhoncus dolor purus non enim praesent.
        Facilisis volutpat est velit egestas dui id ornare. Tortor dignissim convallis aenean et tortor at. Dignissim cras tincidunt lobortis feugiat vivamus at augue. Quis lectus nulla at volutpat diam ut venenatis. In cursus turpis massa tincidunt dui ut ornare. Eget nullam non nisi est sit amet facilisis magna etiam. Arcu bibendum at varius vel pharetra vel turpis nunc eget. Eu nisl nunc mi ipsum faucibus vitae. Ultrices vitae auctor eu augue ut lectus. Tempus urna et pharetra pharetra massa. Netus et malesuada fames ac turpis egestas integer. Posuere ac ut consequat semper viverra nam libero justo laoreet. Aliquam purus sit amet luctus venenatis lectus magna. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Dui id ornare arcu odio ut sem nulla pharetra. Ut lectus arcu bibendum at varius vel. Enim nulla aliquet porttitor lacus luctus accumsan. Nam libero justo laoreet sit. Dui vivamus arcu felis bibendum.
        Congue nisi vitae suscipit tellus. Posuere ac ut consequat semper viverra nam libero justo. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget aliquet nibh praesent tristique magna sit. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis natoque. Arcu risus quis varius quam quisque. Suspendisse in est ante in. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim. At tellus at urna condimentum mattis pellentesque id nibh. Consectetur adipiscing elit duis tristique sollicitudin nibh. Nunc faucibus a pellentesque sit. Mauris vitae ultricies leo integer malesuada. Elit at imperdiet dui accumsan sit amet nulla facilisi morbi. Cursus eget nunc scelerisque viverra. Phasellus faucibus scelerisque eleifend donec pretium.
        Nisl rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Ut sem viverra aliquet eget. Gravida dictum fusce ut placerat orci nulla pellentesque. Aliquam id diam maecenas ultricies mi. Eu non diam phasellus vestibulum lorem sed risus. Libero justo laoreet sit amet cursus sit amet dictum. Et netus et malesuada fames ac turpis egestas sed tempus. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Vitae ultricies leo integer malesuada nunc vel. Ullamcorper sit amet risus nullam eget felis eget nunc. Sed id semper risus in. Dolor sit amet consectetur adipiscing elit ut. Sit amet tellus cras adipiscing enim eu turpis egestas. Ac turpis egestas integer eget aliquet nibh praesent tristique magna.
        Volutpat est velit egestas dui id ornare arcu. Sed risus pretium quam vulputate. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Rhoncus urna neque viverra justo nec ultrices. Sem et tortor consequat id porta nibh. Dolor sit amet consectetur adipiscing elit duis. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Enim ut sem viverra aliquet eget sit amet. Vitae ultricies leo integer malesuada nunc vel risus. Tincidunt augue interdum velit euismod in. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Pretium aenean pharetra magna ac placerat vestibulum lectus. Maecenas pharetra convallis posuere morbi leo urna molestie. At lectus urna duis convallis convallis tellus id interdum velit.
        Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Tortor posuere ac ut consequat semper viverra nam libero justo. Nisl vel pretium lectus quam. Adipiscing enim eu turpis egestas pretium aenean. Sit amet consectetur adipiscing elit duis tristique sollicitudin. Enim nulla aliquet porttitor lacus luctus. Dolor magna eget est lorem ipsum dolor sit. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Id donec ultrices tincidunt arcu. Magna etiam tempor orci eu lobortis. Lectus proin nibh nisl condimentum. Enim diam vulputate ut pharetra sit amet aliquam id diam. Dolor sit amet consectetur adipiscing. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Congue quisque egestas diam in arcu cursus euismod quis. Ipsum consequat nisl vel pretium lectus. At volutpat diam ut venenatis. Risus nec feugiat in fermentum posuere.
        Risus viverra adipiscing at in tellus integer feugiat scelerisque varius. Ut diam quam nulla porttitor massa id. Eu tincidunt tortor aliquam nulla facilisi cras fermentum. In ante metus dictum at tempor. Ac tortor vitae purus faucibus. Ut ornare lectus sit amet. Mus mauris vitae ultricies leo integer malesuada nunc vel risus. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Duis ut diam quam nulla porttitor.
        Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Bibendum neque egestas congue quisque egestas diam in. Vulputate mi sit amet mauris commodo quis. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Mattis vulputate enim nulla aliquet porttitor. Neque gravida in fermentum et sollicitudin ac orci. Odio aenean sed adipiscing diam. Adipiscing at in tellus integer feugiat scelerisque varius morbi. Dui id ornare arcu odio ut sem nulla. Pellentesque id nibh tortor id. Sit amet nulla facilisi morbi tempus iaculis urna id. Volutpat odio facilisis mauris sit. Integer eget aliquet nibh praesent tristique. Ac placerat vestibulum lectus mauris ultrices eros in. Maecenas sed enim ut sem.
    </section>
    <section id="page2">
        <h1>PAGE 2</h1>
        this is a section.

        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sagittis vitae et leo duis. Sed risus pretium quam vulputate dignissim suspendisse in est. Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Lacus laoreet non curabitur gravida arcu ac. Est ante in nibh mauris cursus. Viverra mauris in aliquam sem. Justo laoreet sit amet cursus sit amet dictum sit amet. Turpis egestas pretium aenean pharetra. Ut enim blandit volutpat maecenas volutpat. Odio ut sem nulla pharetra diam sit. Felis imperdiet proin fermentum leo vel orci porta. Et pharetra pharetra massa massa. Arcu risus quis varius quam quisque id. Tempus urna et pharetra pharetra massa massa ultricies mi. Nisl nisi scelerisque eu ultrices. Sed velit dignissim sodales ut eu. Porttitor rhoncus dolor purus non enim praesent.
        Facilisis volutpat est velit egestas dui id ornare. Tortor dignissim convallis aenean et tortor at. Dignissim cras tincidunt lobortis feugiat vivamus at augue. Quis lectus nulla at volutpat diam ut venenatis. In cursus turpis massa tincidunt dui ut ornare. Eget nullam non nisi est sit amet facilisis magna etiam. Arcu bibendum at varius vel pharetra vel turpis nunc eget. Eu nisl nunc mi ipsum faucibus vitae. Ultrices vitae auctor eu augue ut lectus. Tempus urna et pharetra pharetra massa. Netus et malesuada fames ac turpis egestas integer. Posuere ac ut consequat semper viverra nam libero justo laoreet. Aliquam purus sit amet luctus venenatis lectus magna. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Dui id ornare arcu odio ut sem nulla pharetra. Ut lectus arcu bibendum at varius vel. Enim nulla aliquet porttitor lacus luctus accumsan. Nam libero justo laoreet sit. Dui vivamus arcu felis bibendum.
        Congue nisi vitae suscipit tellus. Posuere ac ut consequat semper viverra nam libero justo. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget aliquet nibh praesent tristique magna sit. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis natoque. Arcu risus quis varius quam quisque. Suspendisse in est ante in. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim. At tellus at urna condimentum mattis pellentesque id nibh. Consectetur adipiscing elit duis tristique sollicitudin nibh. Nunc faucibus a pellentesque sit. Mauris vitae ultricies leo integer malesuada. Elit at imperdiet dui accumsan sit amet nulla facilisi morbi. Cursus eget nunc scelerisque viverra. Phasellus faucibus scelerisque eleifend donec pretium.
        Nisl rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Ut sem viverra aliquet eget. Gravida dictum fusce ut placerat orci nulla pellentesque. Aliquam id diam maecenas ultricies mi. Eu non diam phasellus vestibulum lorem sed risus. Libero justo laoreet sit amet cursus sit amet dictum. Et netus et malesuada fames ac turpis egestas sed tempus. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Vitae ultricies leo integer malesuada nunc vel. Ullamcorper sit amet risus nullam eget felis eget nunc. Sed id semper risus in. Dolor sit amet consectetur adipiscing elit ut. Sit amet tellus cras adipiscing enim eu turpis egestas. Ac turpis egestas integer eget aliquet nibh praesent tristique magna.
        Volutpat est velit egestas dui id ornare arcu. Sed risus pretium quam vulputate. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Rhoncus urna neque viverra justo nec ultrices. Sem et tortor consequat id porta nibh. Dolor sit amet consectetur adipiscing elit duis. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Enim ut sem viverra aliquet eget sit amet. Vitae ultricies leo integer malesuada nunc vel risus. Tincidunt augue interdum velit euismod in. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Pretium aenean pharetra magna ac placerat vestibulum lectus. Maecenas pharetra convallis posuere morbi leo urna molestie. At lectus urna duis convallis convallis tellus id interdum velit.
        Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Tortor posuere ac ut consequat semper viverra nam libero justo. Nisl vel pretium lectus quam. Adipiscing enim eu turpis egestas pretium aenean. Sit amet consectetur adipiscing elit duis tristique sollicitudin. Enim nulla aliquet porttitor lacus luctus. Dolor magna eget est lorem ipsum dolor sit. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Id donec ultrices tincidunt arcu. Magna etiam tempor orci eu lobortis. Lectus proin nibh nisl condimentum. Enim diam vulputate ut pharetra sit amet aliquam id diam. Dolor sit amet consectetur adipiscing. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Congue quisque egestas diam in arcu cursus euismod quis. Ipsum consequat nisl vel pretium lectus. At volutpat diam ut venenatis. Risus nec feugiat in fermentum posuere.
        Risus viverra adipiscing at in tellus integer feugiat scelerisque varius. Ut diam quam nulla porttitor massa id. Eu tincidunt tortor aliquam nulla facilisi cras fermentum. In ante metus dictum at tempor. Ac tortor vitae purus faucibus. Ut ornare lectus sit amet. Mus mauris vitae ultricies leo integer malesuada nunc vel risus. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Duis ut diam quam nulla porttitor.
        Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Bibendum neque egestas congue quisque egestas diam in. Vulputate mi sit amet mauris commodo quis. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Mattis vulputate enim nulla aliquet porttitor. Neque gravida in fermentum et sollicitudin ac orci. Odio aenean sed adipiscing diam. Adipiscing at in tellus integer feugiat scelerisque varius morbi. Dui id ornare arcu odio ut sem nulla. Pellentesque id nibh tortor id. Sit amet nulla facilisi morbi tempus iaculis urna id. Volutpat odio facilisis mauris sit. Integer eget aliquet nibh praesent tristique. Ac placerat vestibulum lectus mauris ultrices eros in. Maecenas sed enim ut sem.
    </section>
    <section id="pageL">
        <h1>PAGE L</h1>
        this is a section.

        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sagittis vitae et leo duis. Sed risus pretium quam vulputate dignissim suspendisse in est. Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Lacus laoreet non curabitur gravida arcu ac. Est ante in nibh mauris cursus. Viverra mauris in aliquam sem. Justo laoreet sit amet cursus sit amet dictum sit amet. Turpis egestas pretium aenean pharetra. Ut enim blandit volutpat maecenas volutpat. Odio ut sem nulla pharetra diam sit. Felis imperdiet proin fermentum leo vel orci porta. Et pharetra pharetra massa massa. Arcu risus quis varius quam quisque id. Tempus urna et pharetra pharetra massa massa ultricies mi. Nisl nisi scelerisque eu ultrices. Sed velit dignissim sodales ut eu. Porttitor rhoncus dolor purus non enim praesent.
        Facilisis volutpat est velit egestas dui id ornare. Tortor dignissim convallis aenean et tortor at. Dignissim cras tincidunt lobortis feugiat vivamus at augue. Quis lectus nulla at volutpat diam ut venenatis. In cursus turpis massa tincidunt dui ut ornare. Eget nullam non nisi est sit amet facilisis magna etiam. Arcu bibendum at varius vel pharetra vel turpis nunc eget. Eu nisl nunc mi ipsum faucibus vitae. Ultrices vitae auctor eu augue ut lectus. Tempus urna et pharetra pharetra massa. Netus et malesuada fames ac turpis egestas integer. Posuere ac ut consequat semper viverra nam libero justo laoreet. Aliquam purus sit amet luctus venenatis lectus magna. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Dui id ornare arcu odio ut sem nulla pharetra. Ut lectus arcu bibendum at varius vel. Enim nulla aliquet porttitor lacus luctus accumsan. Nam libero justo laoreet sit. Dui vivamus arcu felis bibendum.
        Congue nisi vitae suscipit tellus. Posuere ac ut consequat semper viverra nam libero justo. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Eget aliquet nibh praesent tristique magna sit. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis natoque. Arcu risus quis varius quam quisque. Suspendisse in est ante in. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim. At tellus at urna condimentum mattis pellentesque id nibh. Consectetur adipiscing elit duis tristique sollicitudin nibh. Nunc faucibus a pellentesque sit. Mauris vitae ultricies leo integer malesuada. Elit at imperdiet dui accumsan sit amet nulla facilisi morbi. Cursus eget nunc scelerisque viverra. Phasellus faucibus scelerisque eleifend donec pretium.
        Nisl rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Ut sem viverra aliquet eget. Gravida dictum fusce ut placerat orci nulla pellentesque. Aliquam id diam maecenas ultricies mi. Eu non diam phasellus vestibulum lorem sed risus. Libero justo laoreet sit amet cursus sit amet dictum. Et netus et malesuada fames ac turpis egestas sed tempus. Eu lobortis elementum nibh tellus molestie nunc non blandit massa. Vitae ultricies leo integer malesuada nunc vel. Ullamcorper sit amet risus nullam eget felis eget nunc. Sed id semper risus in. Dolor sit amet consectetur adipiscing elit ut. Sit amet tellus cras adipiscing enim eu turpis egestas. Ac turpis egestas integer eget aliquet nibh praesent tristique magna.
        Volutpat est velit egestas dui id ornare arcu. Sed risus pretium quam vulputate. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Rhoncus urna neque viverra justo nec ultrices. Sem et tortor consequat id porta nibh. Dolor sit amet consectetur adipiscing elit duis. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Enim ut sem viverra aliquet eget sit amet. Vitae ultricies leo integer malesuada nunc vel risus. Tincidunt augue interdum velit euismod in. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Pretium aenean pharetra magna ac placerat vestibulum lectus. Maecenas pharetra convallis posuere morbi leo urna molestie. At lectus urna duis convallis convallis tellus id interdum velit.
        Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Tortor posuere ac ut consequat semper viverra nam libero justo. Nisl vel pretium lectus quam. Adipiscing enim eu turpis egestas pretium aenean. Sit amet consectetur adipiscing elit duis tristique sollicitudin. Enim nulla aliquet porttitor lacus luctus. Dolor magna eget est lorem ipsum dolor sit. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Id donec ultrices tincidunt arcu. Magna etiam tempor orci eu lobortis. Lectus proin nibh nisl condimentum. Enim diam vulputate ut pharetra sit amet aliquam id diam. Dolor sit amet consectetur adipiscing. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Congue quisque egestas diam in arcu cursus euismod quis. Ipsum consequat nisl vel pretium lectus. At volutpat diam ut venenatis. Risus nec feugiat in fermentum posuere.
        Risus viverra adipiscing at in tellus integer feugiat scelerisque varius. Ut diam quam nulla porttitor massa id. Eu tincidunt tortor aliquam nulla facilisi cras fermentum. In ante metus dictum at tempor. Ac tortor vitae purus faucibus. Ut ornare lectus sit amet. Mus mauris vitae ultricies leo integer malesuada nunc vel risus. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Duis ut diam quam nulla porttitor.
        Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Bibendum neque egestas congue quisque egestas diam in. Vulputate mi sit amet mauris commodo quis. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Mattis vulputate enim nulla aliquet porttitor. Neque gravida in fermentum et sollicitudin ac orci. Odio aenean sed adipiscing diam. Adipiscing at in tellus integer feugiat scelerisque varius morbi. Dui id ornare arcu odio ut sem nulla. Pellentesque id nibh tortor id. Sit amet nulla facilisi morbi tempus iaculis urna id. Volutpat odio facilisis mauris sit. Integer eget aliquet nibh praesent tristique. Ac placerat vestibulum lectus mauris ultrices eros in. Maecenas sed enim ut sem.
    </section>
    </>);
}

export default LayoutTest;